-- ============================================
-- Phase 4: CEO Agent Orchestration System
-- Workflow tracking and agent self-replication
-- ============================================

-- Workflow executions (CEO Agent orchestrated tasks)
CREATE TABLE IF NOT EXISTS agent_workflows (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  user_prompt TEXT NOT NULL,  -- Original human request
  status TEXT CHECK (status IN ('planning', 'pending_approval', 'saved', 'running', 'completed', 'failed', 'cancelled')) DEFAULT 'planning',
  current_step INTEGER DEFAULT 0,
  total_steps INTEGER,
  workflow_plan JSONB,  -- GPT-5.2 generated plan
  started_at TIMESTAMP,
  completed_at TIMESTAMP,
  total_cost_usd NUMERIC(10, 4) DEFAULT 0,
  results JSONB,  -- Aggregated results from all steps
  executive_summary TEXT,  -- GPT-5.2 generated summary
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Link child executions to parent workflow
ALTER TABLE agent_executions
  ADD COLUMN IF NOT EXISTS workflow_id UUID REFERENCES agent_workflows(id),
  ADD COLUMN IF NOT EXISTS step_order INTEGER;

-- Human approval gates
CREATE TABLE IF NOT EXISTS workflow_approvals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workflow_id UUID REFERENCES agent_workflows(id),
  step_order INTEGER,
  approval_type TEXT CHECK (approval_type IN ('pre_execution', 'post_validation', 'critical_action', 'agent_creation')) DEFAULT 'critical_action',
  prompt TEXT NOT NULL,  -- What to show user
  context JSONB,  -- Additional data for decision (e.g., generated code for agent creation)
  status TEXT CHECK (status IN ('pending', 'approved', 'rejected')) DEFAULT 'pending',
  approved_by TEXT,
  approved_at TIMESTAMP,
  notes TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Agent code generations (for audit trail of self-replication)
CREATE TABLE IF NOT EXISTS agent_code_generations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  agent_name TEXT NOT NULL,
  description TEXT,
  capabilities TEXT[],
  generated_code TEXT NOT NULL,
  validation_status TEXT CHECK (validation_status IN ('pending', 'safe', 'unsafe')) DEFAULT 'pending',
  validation_notes TEXT,
  approval_id UUID REFERENCES workflow_approvals(id),
  created_by TEXT DEFAULT 'ceo-agent',
  created_at TIMESTAMP DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS workflows_status_idx ON agent_workflows(status);
CREATE INDEX IF NOT EXISTS workflows_created_idx ON agent_workflows(created_at DESC);
CREATE INDEX IF NOT EXISTS executions_workflow_idx ON agent_executions(workflow_id, step_order);
CREATE INDEX IF NOT EXISTS approvals_pending_idx ON workflow_approvals(workflow_id, status) WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS code_gen_agent_idx ON agent_code_generations(agent_name);

-- Update trigger for updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_workflows_updated_at BEFORE UPDATE ON agent_workflows
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Comments for documentation
COMMENT ON TABLE agent_workflows IS 'CEO Agent orchestrated multi-step workflows';
COMMENT ON TABLE workflow_approvals IS 'Human approval gates for critical workflow actions';
COMMENT ON TABLE agent_code_generations IS 'Audit trail for CEO Agent self-replication (agent creation)';
COMMENT ON COLUMN agent_workflows.workflow_plan IS 'Full workflow plan generated by GPT-5.2 including steps and reasoning';
COMMENT ON COLUMN agent_workflows.executive_summary IS 'GPT-5.2 generated strategic summary after workflow completion';
COMMENT ON COLUMN workflow_approvals.approval_type IS 'agent_creation requires approval for self-replication safety';
COMMENT ON COLUMN agent_code_generations.generated_code IS 'Full Python script generated by GPT-5.2 for new worker agent';
